# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiserver.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(456, 185)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(170, 20, 241, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_ip = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_ip.setObjectName("label_ip")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ip)
        self.label_porta = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_porta.setObjectName("label_porta")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_porta)
        self.textEdit_ip = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.textEdit_ip.setObjectName("textEdit_ip")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEdit_ip)
        self.textEdit_porta = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.textEdit_porta.setObjectName("textEdit_porta")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit_porta)
        self.label_tempo_aberto_m = QtWidgets.QLabel(self.centralwidget)
        self.label_tempo_aberto_m.setGeometry(QtCore.QRect(20, 20, 158, 16))
        self.label_tempo_aberto_m.setObjectName("label_tempo_aberto_m")
        self.label_minutos = QtWidgets.QLabel(self.centralwidget)
        self.label_minutos.setGeometry(QtCore.QRect(40, 50, 158, 16))
        self.label_minutos.setObjectName("label_minutos")
        self.botao_parar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_parar.setGeometry(QtCore.QRect(10, 150, 158, 24))
        self.botao_parar.setObjectName("botao_parar")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(240, 90, 239, 16))
        self.label_status.setObjectName("label_status")
        self.label_ip_botao = QtWidgets.QLabel(self.centralwidget)
        self.label_ip_botao.setGeometry(QtCore.QRect(240, 120, 239, 16))
        self.label_ip_botao.setObjectName("label_ip_botao")
        self.botao_iniciar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_iniciar.setGeometry(QtCore.QRect(200, 150, 239, 24))
        self.botao_iniciar.setObjectName("botao_iniciar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.botao_iniciar.clicked['bool'].connect(self.textEdit_porta.setEnabled) # type: ignore
        self.botao_iniciar.clicked['bool'].connect(self.textEdit_ip.setEnabled) # type: ignore
        self.botao_parar.clicked['bool'].connect(self.textEdit_porta.setDisabled) # type: ignore
        self.botao_parar.clicked['bool'].connect(self.textEdit_ip.setDisabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Servidor de Arquivos - Lucas Rocha"))
        self.label_ip.setText(_translate("MainWindow", "IP:"))
        self.label_porta.setText(_translate("MainWindow", "Porta"))
        self.label_tempo_aberto_m.setText(_translate("MainWindow", "Tempo Servidor Aberto:"))
        self.label_minutos.setText(_translate("MainWindow", "0 minutos"))
        self.botao_parar.setText(_translate("MainWindow", "Parar"))
        self.label_status.setText(_translate("MainWindow", "Status:         Parado"))
        self.label_ip_botao.setText(_translate("MainWindow", "IP:"))
        self.botao_iniciar.setText(_translate("MainWindow", "Clique para iniciar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
